name: Terraform Destroy S3

on: workflow_dispatch

env:            
  AWS_REGION: us-east-1  

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
   
    - name: Terraform Init with Backend
      run: |
        terraform init -backend-config="bucket=joseph-sctps3bucket" \
                       -backend-config="key=joseph03-wk18-3.1" \
                       -backend-config="region=us-east-1"

    #- name: Check for Terraform Lock
    #  run: |
    #    LOCK_ID=$(aws dynamodb scan --table-name terraform-lock-table --query "Items[0].LockID.S" --output text || echo "NO_LOCK")
    #    if [ "$LOCK_ID" != "NO_LOCK" ]; then
    #      terraform force-unlock $LOCK_ID
    #    else
    #      echo "No active lock found."
    #    fi

    - name: Terraform Destroy
      run: terraform destroy --auto-approve

    - name: Remove Terraform State File
      run: aws s3 rm s3://joseph-sctps3bucket/joseph03-wk18-3.1