name: Terraform Deployment

on:
  push:
    branches: [ "main" ]

env:            
  AWS_REGION: us-east-1  

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
    # actoins/checkout will pull codes from repository and put into the runner
    - name: Checkout
      uses: actions/checkout@v3  
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
   
    - name: Terraform Init
      run: terraform init

    # below is not needed for terraform apply as it is provided in tfstate.tf
    #- name: Terraform Init with Backend
    #  run: |
    #    terraform init -backend-config="bucket=joseph-sctps3bucket" \
    #                   -backend-config="key=joseph03-wk18-3.1" \
    #                   -backend-config="region=us-east-1"

    - name: Terraform Plan
      run: terraform plan
   
    - name: Terraform Apply
      run: terraform apply --auto-approve
